---
title: "PCOA phylogeny"
author: "Antdrew D. Nguyen"
date: "2016-June-23"
output: pdf_document
---
```{r libraries}
library(ape)
#library(geiger)
#library(ade4)
#library(adephylo)
library(dplyr)
options(na.action = "na.fail")
```

#NJ tree
```{r NJ tree manipulations}

#read in NJ tree
KMtree<-read.tree("../Data/20160623_Katie_NJ_tree_N6_3SNP_ANBE_mod.nwk")

plot(KMtree)
#excluding
#ABP3,BRP7,BEAR4,CGYM12
length(KMtree$tip.label)
KMtree2<-drop.tip(KMtree,c("ABP3","BRP7","BEAR4","CGYM12"))
length(KMtree2$tip.label)
#looks like only 1 tip dropped out
#ifelse(KMtree$tip.label=="ABP3",1,0)


# getting a distance matrix from branch lengths
bl<-cophenetic(KMtree2)

# pcoa of distance matrix
KMpcoa<-pcoa(bl)


#exploring the pcoa's
knitr::kable(KMpcoa$values[1:10,])

#plotting the first and second axis
plot(KMpcoa$vectors[,1],KMpcoa$vectors[,2])
text(KMpcoa$vectors[,1],KMpcoa$vectors[,2],labels=KMtree2$tip.label)

#the eigenvectors
#KMpcoa$vectors[,1:10]
#write.csv(KMpcoa$vectors[,1:10],"20160623_KM_eigenvectors.csv")


#code for merging eigenvectors into dataset
#setting as dataframe
pcoa.dat<-as.data.frame(KMpcoa$vectors[,1:10])

##This is important, setting a new column with the names of tip labels
pcoa.dat$colonyID2<-KMtree2$tip.label

knitr::kable(head(pcoa.dat[1:4,]))
#merging dataset with ant_dat_clim

#Final.dat1<-inner_join(originaldata,pcoa.dat,by="colony_id_name")

```

#raxml tree
```{r raxml tree manips}
tree2<-read.tree("../Results/20160623_Cipres_RaxML_output/20160623_BL_tree_parsed.newick")

plot(tree2)
KMtree3<-drop.tip(tree2,c("ABP3","BRP7","BEAR4","CGYM12"))
#length(tree2$tip.label)
#length(KMtree3$tip.label)


# getting a distance matrix from branch lengths
bl2<-cophenetic(KMtree3)

# pcoa of distance matrix
KMpcoa2<-pcoa(bl2)
biplot(KMpcoa2)

#plot(KMpcoa$vector[,1],KMpcoa2$vector[,1])
#text(KMpcoa$vector[,1],KMpcoa2$vector[,1],labels=KMtree3$tip.label)
```

```{r Merging Datasets}
#Reading in original dataset (C, N, P averages)
Full_data <-read.csv("../Data/TOTAL_FINAL_DATA_SET_KMBE_v2_07-22-2016.csv")
#Manually renaming colony IDs to match IDs in original dataset
Rename<-read.csv("../Results/20160623_KM_eigenvectors.csv")
#Joining datasets
Final.dat1<-inner_join(Full_data,Rename,by="colonyID2")

#Checking dimensions
dim(Full_data)
dim(Final.dat1)
#54 of the 76 colonies matched


```

```{r, include=False}
#stats
library(MuMIn)
#checking correlation in climate variables
clim.pca<-princomp(scale(Final.dat1[,8:11]))
summary(clim.pca)
clim.pca$loadings[,1:3]
Final.dat1<-cbind(Final.dat1,clim.pca$scores[,1:3])


#construct full model
#c.mod<-lm(C.percent.colony~MAT+DRT+APS+MAP+CN.colony.mass+Axis.1+Axis.2+Axis.3+Axis.4+Axis.5+MAT*Axis.1+MAT*Axis.2+MAT*Axis.3+MAT*Axis.4+MAT*Axis.5+DRT*Axis.1+DRT*Axis.2+DRT*Axis.3+DRT*Axis.4+DRT*Axis.5+APS*Axis.1+APS*Axis.2+APS*Axis.3+APS*Axis.4+APS*Axis.5+MAP*Axis.1+MAP*Axis.2+MAP*Axis.3+MAP*Axis.4+MAP*Axis.5+CN.colony.mass*Axis.1+CN.colony.mass*Axis.2+CN.colony.mass*Axis.3+CN.colony.mass*Axis.4+CN.colony.mass*Axis.5, data=na.omit(Final.dat1))
#c.mod<-lm(C.percent.colony~MAT+DRT+APS+MAP+CN.colony.mass+Axis.1+Axis.2+Axis.3+Axis.1*DRT+Axis.1*APS+Axis.2*DRT+Axis.2*APS+Axis.3*DRT+Axis.3*APS, data=na.omit(Final.dat1))
ef<-lm(C.percent.colony~Axis.1+Axis.2+Axis.3+Axis.4+Axis.5,data=Final.dat1);summary(ef)


c.mod<-lm(C.percent.colony~Comp.1*Axis.2+Comp.2*Axis.2+Comp.3*Axis.2+CN.colony.mass,data=Final.dat1)

summary(c.mod)

# model selection: use dredge function from MuMIn package to grab AIC rankings of subset models
new<-na.omit(Final.dat1)
c.mod2<-lm(C.percent.colony~Comp.1*Axis.2+Comp.2*Axis.2+Comp.3*Axis.2+CN.colony.mass,data=new)
sum.mod<-dredge(c.mod2);sum.mod
plot(sum.mod)


#model selection with MASS package
library(MASS)
summary(stepAIC(c.mod,direction="both"))


```


```{r sessioninfo}
sessionInfo()
```

